### ISSUE TITLE
Designs elsewhere.

### ISSUE THREAD

**Issue by larsbrinkhoff** [larsbrinkhoff/t-shirts#1]
@sharpjs's PDP-10 t-shirt:
https://github.com/PDP-10/documents/tree/master/shirts/sharpjs-pdp-10

**Comment by larsbrinkhoff** [comment]
@sharpjs, you're working on another design, right?  Was it Imlac?

**Comment by sharpjs** [comment]
Yes, I need to dust off the Imlac and post it.

**Comment by sharpjs** [comment]
Feel free to assign to me.

**Comment by larsbrinkhoff** [comment]
Thanks!
